# Generated by Django 4.2.4 on 2023-08-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='category',
            new_name='catagory',
        ),
    ]
