# Generated by Django 4.2.4 on 2023-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_remove_enrolledclasses_student_enrolledclasses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=50)),
                ('numbers', models.CharField(max_length=50)),
                ('msgs', models.TextField()),
            ],
        ),
    ]
